fix(bash): modified file print_list

diff --git a/linux/bash/sample/print_list b/linux/bash/sample/print_list
--- a/linux/bash/sample/print_list
+++ b/linux/bash/sample/print_list
@@ -5,13 +5,13 @@ file_out='./list.out'
 
 # Check if file in is exist and can be read and not empty
 if [ ! -f "$file_in" ] || [ ! -r "$file_in" ] || [ ! -s "$file_in" ]; then
-	printf '%s\n' "Make sure file $file_in is exists, and not empty also had read permission"
+	printf 'Make sure file %s is exists, not empty and also has read permission \n' "$file_in"
 	exit 1
 fi
 
 # check if file out is exist, if exist make sure agree to overwrite,
 if [ -f "$file_out" ] ; then
-	printf "File $file_out is exists, are you sure want to overwrite [y/N] ? "
+	printf 'File %s is exists, are you sure want to overwrite [y/N] ? ' "$file_out"
 	read -r response
 	if [ "${response^}" != 'Y' ] ; then
 		exit 1
@@ -19,8 +19,8 @@ if [ -f "$file_out" ] ; then
 fi
 
 # Initializing file out as an empty file,  exit if failed
-if ! (rm -f "$file_out" && touch "$file_out") ; then
-	printf "ERROR - Failed initializing $file_out \n"
+if ! rm -f "$file_out" && touch "$file_out" ; then
+	printf 'ERROR - Failed initializing %s \n' "$file_out"
 	exit 1
 fi
 
